In [1]:
import numpy as np


# **Array Creation in Numpy**

## 1) np.array([List])

In [7]:
#Using np.array([List]) --> 1D
m = np.array([8,5,4,3,5])
m

array([8, 5, 4, 3, 5])

In [8]:
# #Using np.array([List]) --> 2D
n = np.array([[7,8,9,4],[5,6,1,2]])
n

array([[7, 8, 9, 4],
       [5, 6, 1, 2]])

In [9]:
# #Using np.array([List]) --> 3D
o = np.array([[7,8,9,4],[5,6,1,2],[10,11,12,13]])
o

array([[ 7,  8,  9,  4],
       [ 5,  6,  1,  2],
       [10, 11, 12, 13]])

## 2) np.arange(included, excluded, step)

In [10]:
m = np.arange(0,10)
m

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
n = np.arange(0,10,2)
n


array([0, 2, 4, 6, 8])

# You can use .reshape(row, col)

In [15]:
arr = np.arange(1,9).reshape(4,2)
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

## 3) np.zeros(size) and np.ones(size)

In [25]:
#1D
A = np.zeros(5, dtype = np.int8)
A

array([0, 0, 0, 0, 0], dtype=int8)

In [24]:
#2D
A = np.zeros((5,5), dtype = np.int8)
A

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [28]:
#3D
A = np.ones((2,3,3), dtype = np.int8)
A

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int8)

## 4) np.linspace(starting range, ending range, no of element need)

In [32]:
B = np.linspace(-10, 10, 5, dtype=np.int8)
B

array([-10,  -5,   0,   5,  10], dtype=int8)

## 5) np.random.random(tuple(row,col))

In [33]:
#1D
C = np.random.random(5)
C

array([0.35606219, 0.1550504 , 0.43452715, 0.18296255, 0.63715788])

In [34]:
#2D
C = np.random.random((5,3))
C

array([[0.99510993, 0.20503838, 0.91566174],
       [0.37292153, 0.0229443 , 0.26849226],
       [0.48758952, 0.88285224, 0.40801777],
       [0.35475561, 0.97630888, 0.35895687],
       [0.1814566 , 0.61406707, 0.93997554]])

In [36]:
#3D
D = np.random.random((2,3,2))
D

array([[[0.64100094, 0.23863755],
        [0.21310498, 0.83057691],
        [0.98782197, 0.39559408]],

       [[0.55239403, 0.88885545],
        [0.38372563, 0.89463595],
        [0.6923798 , 0.94472704]]])

## 6) np.identity(size)

In [39]:
E = np,np.identity(5)
E

(<module 'numpy' from '/usr/local/lib/python3.11/dist-packages/numpy/__init__.py'>,
 array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]))