## **Numpy Array Attributes**

# #reshape()
# #ndim
# #shape
# #size
# #itemsize
# #dtype
# #astype

In [1]:
import numpy as np

In [20]:
# reshape
a1 = np.arange(10, dtype = np.int16)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)

In [7]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [9]:
#ndim tell how many dimention your array have
a1.ndim

1

In [10]:
a2.ndim

2

In [11]:
a3.ndim

3

In [12]:
#shape tells you how many row * coloum you have
a3.shape

(2, 2, 2)

In [13]:
a1.shape

(10,)

In [14]:
#size tells that how many element present
a3.size

8

In [15]:
a2.size

12

In [16]:
#itemsize tells each element size
a3.itemsize

8

In [21]:
a1.itemsize

2

In [22]:
#dtype tells data type of your array element
a3.dtype

dtype('int64')

In [26]:
a1.dtype

dtype('int16')

In [27]:
#astype helps to change data type from your present type. but it don't change in
# original array
a1.astype(np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)