# **Numpy Array Functions**

## np.max(arr, axis)
## np.min(arr, axis)
## np.sum(arr, axis)
## np.prod(arr, axis)
## axis for >1D array for selecting row(1)/col(0)

In [4]:
import numpy as np


a1 = np.random.random((3, 3))
a1 = np.round(a1 * 100)

In [5]:
a1

array([[73., 38., 84.],
       [77., 43., 30.],
       [12., 33., 10.]])

In [12]:
# np.max()

print(np.max(a1)) #find maximum from your total array

84.0


In [10]:
print(np.max(a1, axis=0))  #find max from each column

[77. 43. 84.]


In [13]:
# np.min()

print(np.min(a1))  #find minimum from your total array

10.0


In [11]:
print(np.min(a1, axis=1))   #find minimun from each row

[38. 30. 10.]


In [14]:
#  np.prod()

print(np.prod(a1)) #gives total product of entire array

91656097948800.0


In [15]:
print(np.prod(a1, axis=1)) #gives total product of each row

[233016.  99330.   3960.]


In [16]:
#  np.sum()

print(np.sum(a1))

400.0


In [19]:
print(np.sum(a1, axis=0))  #gives total summation of each col

[162. 114. 124.]


## Static Operation

> Mean

> Median

> Std

> Var









In [21]:
print(np.mean(a1))

44.44444444444444


In [22]:
print(np.median(a1, axis=0))

[73. 38. 30.]


In [24]:
print(np.var(a1))

673.5802469135801


## Trigonometric Function


> Sin

> Cos





In [29]:
np.sin(a1)  #give sin value of each element

array([[-0.67677196,  0.29636858,  0.73319032],
       [ 0.99952016, -0.83177474, -0.98803162],
       [-0.53657292,  0.99991186, -0.54402111]])

In [30]:
np.cos(a1[:, 1]) #cosent value of coloum 1

array([ 0.95507364,  0.5551133 , -0.01327675])

# Dot Product

## in dot product within two matrix's one's row need to match other's coloum, then dot product going to happened

In [32]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

In [39]:
a4 = np.dot(a2,a3)
a4

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [40]:
np.shape(a4)

(3, 3)

# Round / Floor / Ceil

In [44]:
a5 = np.random.random((3, 2)) * 100

In [45]:
a5

array([[51.37287168, 17.28151061],
       [84.7615759 , 78.2685985 ],
       [ 5.74385277, 40.83803883]])

In [46]:
np.round(a5)  # Always roundoff the array element's value

array([[51., 17.],
       [85., 78.],
       [ 6., 41.]])

In [47]:
np.floor(a5)  #Always take lower bound of decimal value

array([[51., 17.],
       [84., 78.],
       [ 5., 40.]])

In [48]:
np.ceil(a5)  #Always take upeer bound of decimal value

array([[52., 18.],
       [85., 79.],
       [ 6., 41.]])