# **Array Operations**

## Scaler Operations

In [3]:
import numpy as np

a1 = np.arange(1,13).reshape(4,3)
a2 = np.arange(21,33).reshape(4,3)

In [4]:
a1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
a2

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32]])

In [6]:
#Arithmatic Operation
a1*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [7]:
a1+20

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32]])

In [9]:
a2**2

array([[ 441,  484,  529],
       [ 576,  625,  676],
       [ 729,  784,  841],
       [ 900,  961, 1024]])

In [10]:
a2-20

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
#relational Operation
a1<5 #---> return bool value

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False],
       [False, False, False]])

In [12]:
a1[a1<5] #---> return only true element

array([1, 2, 3, 4])

In [13]:
a2 == 25

array([[False, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False]])

In [14]:
a1[a2 == 25] #-->using a2 value extract output from a1

array([5])

## Vector Operation

In [15]:
a1 + a2

array([[22, 24, 26],
       [28, 30, 32],
       [34, 36, 38],
       [40, 42, 44]])

In [17]:
a2//a1

array([[21, 11,  7],
       [ 6,  5,  4],
       [ 3,  3,  3],
       [ 3,  2,  2]])

In [18]:
a1 * a2

array([[ 21,  44,  69],
       [ 96, 125, 156],
       [189, 224, 261],
       [300, 341, 384]])

In [19]:
a1 ** a2

array([[                  1,             4194304,         94143178827],
       [    281474976710656,  298023223876953125, 4561031516192243712],
       [5059972980857283351,                   0, 5756027422282277481],
       [5076944270305263616, 1349464372445695011,                   0]])

In [20]:
a1 > a2

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])